name: Unit Tests

on: [push, pull_request]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          yarn install 
          yarn test
